const ESTADOS_USUARIO = {
  PENDIENTE: 'PENDIENTE',
  ACTIVO:    'ACTIVO',
  INACTIVO:  'INACTIVO'
};

const ESTADOS_UNIDAD = {
  VACIA:        'VACIA',
  OCUPADA:      'OCUPADA',
  EN_REFACCION: 'EN_REFACCION'
};

const ESTADOS_UNIDAD_RELACION = {
  VIGENTE:   'VIGENTE',
  FINALIZADA:'FINALIZADA'
};

const ESTADOS_INCIDENCIA = {
  ABIERTA:     'ABIERTA',
  EN_PROGRESO: 'EN_PROGRESO',
  RESUELTA:    'RESUELTA',
  CERRADA:     'CERRADA',
  RECHAZADA:   'RECHAZADA',
  CANCELADA:   'CANCELADA'
};

const ESTADOS_TRABAJO = {
  CREADO:       'CREADO',
  ASIGNADO:     'ASIGNADO',
  EN_EJECUCION: 'EN_EJECUCION',
  FINALIZADO:   'FINALIZADO',
  CERRADO:      'CERRADO',
  CANCELADO:    'CANCELADO'
};

const ESTADOS_INSTANCIA = {
  PROGRAMADA: 'PROGRAMADA',
  EN_CURSO:   'EN_CURSO',
  CERRADA:    'CERRADA'
};

const TIPOS_GASTO = {
  CORRECTIVO: 'CORRECTIVO',
  PREVENTIVO: 'PREVENTIVO',
  MANUAL:     'MANUAL'
};

const ROLES_UNIDAD = {
  PROPIETARIO: 'PROPIETARIO',
  INQUILINO:   'INQUILINO'
};

const TIPOS_USUARIO = {
  ADMINISTRADOR: 'administrador',
  OCUPANTE:      'ocupante',
  PROVEEDOR:     'proveedor'
};

module.exports = {
  ESTADOS_USUARIO,
  ESTADOS_UNIDAD,
  ESTADOS_UNIDAD_RELACION,
  ESTADOS_INCIDENCIA,
  ESTADOS_TRABAJO,
  ESTADOS_INSTANCIA,
  TIPOS_GASTO,
  ROLES_UNIDAD,
  TIPOS_USUARIO
};